apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name | quote }}
spec:
  host: myapp.ose39apps.levvel-labs.io
  path: "/myapp"
  to:
    kind: Service
    name: {{ .Values.name | quote }}
