apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name | quote }}
spec:
  clusterIP:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentConfig: {{ .Values.name | quote }}
  sessionAffinity: None
  type: ClusterIP
